### ISSUE TITLE
books don't deploy

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/projects#2]
Error because of 404 doesn't helpt me too much: @BSchilperoort do you see where I go wrong?

**Comment by BSchilperoort** [comment]
You skipped step 5 in the guide :) https://github.com/TeachBooks/template

I had changed this in the teaching-matrials repo, so that's why you didn't have to do it there.

Anyway, [books are building now](http://www.ewatercycle.org/projects/)!
